name: PHP Check

on:
  push:
    branches:
      - release-2.1
  pull_request:

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: php -v

    - name: Run Script
      run: |
        php ./check-signed-off.php > check-signed-off.txt 2>&1
        echo "MESSAGE=$OUTPUT" >> $GITHUB_ENV
        echo "$OUTPUT" >> $GITHUB_STEP_SUMMARY

    - name: Get coverage output
      id: get_coverage
      run: echo "::set-output name=coverage::$(check-signed-off.txt)"
    
    - name: Post result to PR
      uses: mshick/add-pr-comment@v1
      if: env.MESSAGE != ''
      with:
        message: ${{ env.MESSAGE }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
        allow-repeats: true # This is the default

    - name: Fail If we had a message
      if: env.MESSAGE != ''
      run: |
        echo "$env.MESSAGE"
        exit 1