name: PHP Check

on:
  push:
    branches:
      - release-2.1
  pull_request:

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: php -v

    - name: Run Script
      run: |
        php ./check-signed-off.php > check-signed-off.txt 2>&1
        cat check-signed-off.txt >> $GITHUB_OUTPUT
        echo "$GITHUB_OUTPUT" >> $GITHUB_STEP_SUMMARY
    
    - name: Post result to PR
      uses: mshick/add-pr-comment@v1
      if: env.GITHUB_OUTPUT != ''
      with:
        message-path: ${{ env.GITHUB_OUTPUT }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
        allow-repeats: true # This is the default

    - name: Fail If we had a message
      if: env.GITHUB_OUTPUT != ''
      run: |
        echo "$env.GITHUB_OUTPUT"
        exit 1