name: PHP Check

on:
  push:
    branches:
      - release-2.1
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: php -v

    - name: Run Script
      run: |
        OUTPUT=$(php ./check-smf-index.php)
        #OUTPUT=$(shell command or script to extract the part your want)
        echo "MESSAGE=$OUTPUT" >> $GITHUB_ENV

    - name: Post result to PR
      uses: mshick/add-pr-comment@v1
      with:
        message: ${{ env.MESSAGE }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
        allow-repeats: false # This is the default