name: PHP Check

on:
  push:
    branches:
      - release-2.1
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: php -v

    - name: Run Script
      run: |
        OUTPUT=$(php ./check-smf-index.php)
        echo "MESSAGE=$OUTPUT" >> $GITHUB_ENV
        echo "$OUTPUT" >> $GITHUB_STEP_SUMMARY

    - name: Post result to PR
      uses: mshick/add-pr-comment@v1
      if: env.MESSAGE != ''
      with:
        message: ${{ env.MESSAGE }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
        allow-repeats: true # This is the default

    - name: Fail If we had a message
      if: env.MESSAGE != ''
      run: |
        echo "$env.MESSAGE"
        exit 1